# Generated by Django 5.2.8 on 2025-11-15 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0003_remove_produto_descricao_alter_categoria_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('novo', 'Novo'), ('aguardando_pagamento', 'Aguardando pagamento'), ('pago', 'Pago'), ('processando', 'Processando'), ('enviado', 'Enviado'), ('entregue', 'Entregue'), ('cancelado', 'Cancelado')], default='novo', max_length=30),
        ),
    ]
