# Generated by Django 5.2.8 on 2025-11-15 22:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja_app', '0004_remove_pedido_usuario_pedido_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='produto',
            name='prazo_entrega',
            field=models.CharField(blank=True, help_text='Ex.: "5 dias úteis", "Pronta entrega", etc.', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(blank=True, choices=[('P', 'P'), ('M', 'M'), ('G', 'G'), ('GG', 'GG')], help_text='Use apenas para produtos da categoria "Camisas".', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='loja_app.categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
